### ISSUE TITLE
Move ConvertToSize function into FormatArgument trait

### ISSUE THREAD

**Issue by oberien** [vstojkovic/rt-format#4]
In https://github.com/vstojkovic/rt-format/issues/2#issuecomment-1025198508 you stated that you'd like to make the user optionally implement `ConvertToSize::convert` and use a default implementation if the user doesn't. This could be achieved by moving the function into the `FormatArgument` trait with a default implementation. Users can then override the default implementation in their `FormatArgument` implementation. Of course this would be a breaking change. Is this a solution you'd be happy with?

**Comment by vstojkovic** [comment]
That's an excellent idea! The reason why I put the conversion into a separate trait is because I didn't want to require everyone to implement it, but providing a default implementation solves that problem. I'll do that.

**Comment by vstojkovic** [comment]
Done!

**Comment by tsdh** [comment]
Nice, now I could drop my always-`Err`-ing `TryInto<usize>` implementation. :-)
